### ISSUE TITLE
filter on mime type / file extension

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/unifile#100]
Hello
I guess many services offer to filter by mime type or file extensions
Do you think we should add that to readdir function? Or filter after getting the result is better?

**Comment by JbIPS** [comment]
If we want to stick to the Node FS API, we should do it after getting the listing. But I have to admit that would generate a lot of calls...

I'm always wondering about a plugin/extension system, maybe that could be the first use case !

**Comment by lexoyo** [comment]
[what I did here in cloud explorer](https://github.com/lexoyo/CloudExplorer2/commit/2224f1b999e0135994413d5e35b8f31ffc2563cf#diff-84f33654499d3ccc0e6dbe58280b4667R88) for now seems good to me after all
```
res.send(result.filter(file => file.isDir || extensions.includes(Path.extname(file.name).toLowerCase())));
```
