### ISSUE TITLE
dropbox does not overwrite files

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/unifile#105]
When I use `writeFile` to write an existing file on Dropbox I have this error returned in the body of dropbox request
```
{"error_summary": "path/conflict/file/...", "error": {".tag": "path", "reason": {".tag": "conflict", "conflict": {".tag": "file"}}, "upload_session_id": "AAAAAAAACj-xxxxxxx"}} 
```
This is a bug right? I can't find where to put the `mode: 'overwrite'` option described here
https://www.dropbox.com/developers/documentation/http/documentation

**Comment by JbIPS** [comment]
Yes it is ! Maybe we should set overwrite to be the new default. Or use flags as in `Fs`? But this would change the API :/

**Comment by lexoyo** [comment]
Do you know where I should add the `mode: 'overwrite'`? I tried but did not find the right spot

**Comment by lexoyo** [comment]
Hi
I tried the default setting as well as the "writeMode: 'overwrite'" setting and it still does not overwrite files
Could you confirm it works on your side please?

**Comment by lexoyo** [comment]
it looks like it doesn't work in batch only
