### ISSUE TITLE
npm dependencies versions

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/unifile#112]
We shiould use an exact version for our modules in package.json
I just had a module breaking my build

**Comment by JbIPS** [comment]
Which one? I'm not very fond of fixed version but maybe we could ship a package-lock.json file with our releases.

**Comment by lexoyo** [comment]
> Which one? 
Mime, see this commit
https://github.com/silexlabs/unifile/commit/8ec996bf33653af2d99b760d5455abf6dacbbb1e

> I'm not very fond of fixed version but maybe we could ship a package-lock.json file with our releases.
👍

**Comment by JbIPS** [comment]
Something weird happened. I'm the one who installed a new major on `mime` on commit f942a4769efea214f702e8bcb995d053279cde6. I missed Dropbox and since it's not tested enough, it slipped through.

Why did I failed.on your hand and not on CI...I've no idea

**Comment by JbIPS** [comment]
Closing it since it looks like the problem came from an hazardous merge rather than a npm dependency
