### ISSUE TITLE
Dropbox: missing required field 'async_job_id'

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/unifile#114]
Hello
When I delete a folder from Dropbox I have this error: `missing required field 'async_job_id'`
Do you know where it comes from?

**Comment by JbIPS** [comment]
Never saw that, it must be something special for big file.

I actually use those ids for batch job, maybe you can use some functions there. 
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by lexoyo** [comment]
> Never saw that, it must be something special for big file. 

it is when I delete a folder

**Comment by lexoyo** [comment]
> it is when I delete a folder

and a file too

**Comment by lexoyo** [comment]
and I suspect that it happens also when I call write file with batch too

**Comment by JbIPS** [comment]
I created a PR to fix that. It works on my machine but I'm not in very good conditions, could you try on yours? If it works too, merge it 😉

**Comment by lexoyo** [comment]
oups, i saw your message too late
now it says 
`Error in unifile Error in call to API function "files/upload_session/finish_batch": request body: entries.commit.mode: missing '.tag' key`

**Comment by lexoyo** [comment]
just a reminder, the dropbox batch issue is still here
do you reproduce the new error ?

**Comment by lexoyo** [comment]
So this should be fixed now that #120 is merged? even the "missing '.tag' key" ?

**Comment by JbIPS** [comment]
I reproduced the issue and fix it on a branch. It will be soon ready to merge to close this issue.

**Comment by lexoyo** [comment]
Great!
