### ISSUE TITLE
FTP stat is wrong

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/unifile#127]
On my machine, the stat of FTP returns a list of files without the '.' folder, so [`folder` is null here](https://github.com/silexlabs/unifile/blob/master/lib/unifile-ftp.js#L167)

**Comment by JbIPS** [comment]
Could you give more context?

* Which FTP server are you talking about? On which OS?
* Could you send me the output (i.e. the list of files) of the request?

Thank you

**Comment by lexoyo** [comment]
Hi
I just started with a fresh install of fedora which is shipped with vsftpd
Right now FTP is not working, waiting for this fix https://github.com/silexlabs/CloudExplorer2/pull/34
But even with the fix, nothing is working locally but the listing of folders... No writing at all nor creating folders and it is unclear what is happening
I'll need testers as soon as the fix is merged

**Comment by lexoyo** [comment]
With an FTP from OVH, it seems to work but when I upload an image and then download it (all with CE), it is corrupted

Can you reproduce?

**Comment by lexoyo** [comment]
Also delete a non empty folder still doesn't work

**Comment by lexoyo** [comment]
And to stick with the stat issue, I reproduce the stat bug with OVH mutu

**Comment by lexoyo** [comment]
to summerize

FTP ovh mutu
* ls works
* write files do not work
* create folders do not work
* stat do not work
* please test upload etc.

Thank you

**Comment by JbIPS** [comment]
I had some problems on WIndows with the current FTP client (cf https://github.com/mscdex/node-ftp/issues/126) so I switch to [JSFTP](https://www.npmjs.com/package/jsftp) and I'm still adjusting the code to this new lib.

**Comment by JbIPS** [comment]
Closed by #136
