### ISSUE TITLE
Accents and Dropbox's writeFile

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/unifile#130]
I use accents in a string like `La France Généalogique` and I pass it to writeFile to write the string to a file. It works well with the fs connector but it does nothing with the Dropbox connector: it does not write anything and it does not fire an error...

**Comment by JbIPS** [comment]
You shouldn't use accents! Please remove them.

Seriously, is it the filename or the content? I'll take a look on the encoding method in Dropbox.

Ideally, could you write that in the Dropbox UT? Even if you let it failing.

Thank you

**Comment by lexoyo** [comment]
The content
I did not test accents in file names

**Comment by lexoyo** [comment]
JB is huge!!

**Comment by JbIPS** [comment]
That's weird, I cannot reproduce it in the test (see https://github.com/silexlabs/unifile/commit/18bfb895810738979fb7bce40b191f455f027218). 

Could you give me more precision or a sample of your program?

**Comment by lexoyo** [comment]
It is the same code as the example here
https://github.com/silexlabs/unifile/issues/131

And the full code is in silex here
https://github.com/silexlabs/Silex/blob/develop/dist/server/Publisher.js

I will test your test code but if you have any idea on how to fix this let me know

**Comment by JbIPS** [comment]
So you're calling it via the `batch` interface?

**Comment by lexoyo** [comment]
Yes

**Comment by lexoyo** [comment]
Thank you!
