### ISSUE TITLE
Accented char in file name error with Dropbox

### ISSUE THREAD

**Issue by JbIPS** [silexlabs/unifile#134]
Due to the filename passed in the header of the request, UTF-8 char are not allowed. When setting the header of the request, we should convert them all to URL-safe chars.

Still interested in fixing it @zurukgit ?

**Comment by SouroucheB** [comment]
Fixing is my duty dude ! Let me handle that :) !

**Comment by JbIPS** [comment]
How is it going? Did you make any progress? Can I help?
