### ISSUE TITLE
Idempotency?

### ISSUE THREAD

**Issue by Analogreality** [silexlabs/unifile#26]
GET    /api/v1.0/dropbox/exec/rm/path/to/folder-or-file/         remove a file or directory

Is this okay?

**Comment by lexoyo** [comment]
Yes it is

**Comment by lexoyo** [comment]
But I think that it is not idempotent because the second time you call it, it will tell you that the file does not exist anymore

**Comment by KrishnaPG** [comment]
Usually requests that modify the resources (such as create, delete, update...) are better kept for POST. It is conventional for users to expect GET requests to be read-only.

**Comment by lexoyo** [comment]
Yes you are right we should change that

**Comment by Analogreality** [comment]
I don't mean to pick fleas off your project.. Just pointing out a concern.
Awesome project BTW.

**Comment by lexoyo** [comment]
:+1: 
we should definitely go for a v1 soon if there we more developers involved

**Comment by JbIPS** [comment]
To be picky, there is a HTTP verb for deletion: DELETE

**Comment by JbIPS** [comment]
Old issue, but it will be taken into account for next version :wink:
