### ISSUE TITLE
License

### ISSUE THREAD

**Issue by KrishnaPG** [silexlabs/unifile#28]
Could you please reconsider the license?

MIT, BSD or Apahce 2 would be more apt for this. I see Cloud Explorer (which is using this) is already using MIT.

**Comment by lexoyo** [comment]
Hello @KrishnaPG 
Yes you are right, for this kind of "lib", MIT is better. 
And I see in package.json that it is MIT... So it is fixed now :+1: 
https://github.com/silexlabs/unifile/blob/master/readme.md#license

**Comment by KrishnaPG** [comment]
Thank you @lexoyo 

This is good work and you guys are doing great job. Now with officially dubbed as MIT-licensed, I will see what I can do to promote this. This certainly deserves better attention.

**Comment by lexoyo** [comment]
:+1:
