### ISSUE TITLE
path missing / in the default config after __dirname

### ISSUE THREAD

**Issue by KrishnaPG** [silexlabs/unifile#29]
Not really major problem, but came across this and thought of notifying it:

In the `lib/default-config.js` file
*    on two lines, the path is missing the start "/" after `__dirname + ` (since __dirname does not end with `/` it is causing the paths such as `/lib../`). 

![image](https://cloud.githubusercontent.com/assets/4610831/10695823/64f3b3b6-79c3-11e5-8060-4c90d29a6f02.png)

*    At [line 31](https://github.com/silexlabs/unifile/blob/master/lib/default-config.js#L31) `path: __dirname + '../../unifile-assets/'`
  *    it should be `path: __dirname + '/../../unifile-assets/'`
*    At [line 39](https://github.com/silexlabs/unifile/blob/master/lib/default-config.js#L39) `ROOT : __dirname + '../../www',`
  *   it should read `ROOT : __dirname + '/../../www',` 

Other lines seem to be fine.

**Comment by KrishnaPG** [comment]
Looks like functionality is not affected by the lack of `/` though.

**Comment by lexoyo** [comment]
oh this is strange
i'll take care of this just in case

**Comment by JbIPS** [comment]
I think we can go a litter farther and use the recommended [`path.join()`](https://nodejs.org/docs/latest-v0.10.x/api/path.html#path_path_join_path1_path2) so it will take care of that AND be Windows compatible :wink:
