### ISSUE TITLE
auth templates 

### ISSUE THREAD

**Issue by KrishnaPG** [silexlabs/unifile#30]
The current `www-auth` template has problems rendering nicely on different screen sizes. The below screenshot presents the problem (when loading it on the fly inside a modal popup in bootstrap).

![image](https://cloud.githubusercontent.com/assets/4610831/10709700/fa53ebd2-7a55-11e5-9c77-a597fc6d22d6.png)

The `login.css` has few hardcoded styles (such as width, margin etc.) that I modified as below and it looks now decent enough with different screen sizes.  Unable to attach the modified css file here, hence pasting the modified css content below.

````
.logo{
  width: 32px;
  height: 32px;
  background-repeat: no-repeat;
  background-size: cover;
}
.logo-ftp{
  background-image: url('/unifile-assets/services/ftp.png');
}
.logo-www{
  background-image: url('/unifile-assets/services/www.png');
}
.main-container {    
  display: inline-block;
  padding: 25px;
  border: 1px solid #D9D9D9;
  -webkit-border-radius: 12px;
  -moz-border-radius: 12px;
  -ms-border-radius: 12px;
  -o-border-radius: 12px;
  border-radius: 12px;
}
.inner-container{
  font-weight: normal;  
  display: inline-block;  
  text-align: left;
}
.title{
  font-size: 18px;
  font-weight: normal;
}
.all-text{
  color: rgb(61, 70, 77);
  font-family: 'Open Sans', 'lucida grande', 'Segoe UI', arial, verdana, 'lucida sans unicode', tahoma, sans-serif;
  font-size: 14px;
  text-align: center;
}
````
With the modifications now, the bootstrap model looks as below (width/height automatically adjusted itself):
![image](https://cloud.githubusercontent.com/assets/4610831/10709754/ae41d6e4-7a57-11e5-9ae9-1b9405eb46a9.png)

On a narrow screen it looks like below (no more scrollbars):

![image](https://cloud.githubusercontent.com/assets/4610831/10709757/d920e986-7a57-11e5-94cc-a64852922d43.png)

**Comment by lexoyo** [comment]
That's great thank you
You should make a pull request to contribute, do you want me to explain how to do it?

**Comment by KrishnaPG** [comment]
Thanks @lexoyo . Created this PR https://github.com/silexlabs/unifile/pull/31

**Comment by lexoyo** [comment]
Merged! Good job mate :)
