### ISSUE TITLE
Graceful error handling while ls

### ISSUE THREAD

**Issue by KrishnaPG** [silexlabs/unifile#32]
For the `www` service, if any directory entry has permission issue, `ls` is failing completely, throwing below style of error, instead of gracefully handling it and moving on.
````
  express:router anonymous /api : /api/v1.0/www/exec/ls/ +1ms
{ [Error: EPERM, operation not permitted '\ui\index.html~RFbbf65e4e.TMP']
  errno: -4048,
  code: 'EPERM',
  path: '\ui\\index.html~RFbbf65e4e.TMP',
  syscall: 'stat' }
error code  500 { success: false,
  message:
   { [Error: EPERM, operation not permitted '\ui\index.html~RFbbf65e4e.TMP']
     errno: -4048,
     code: 'EPERM',
     path: '\ui\\index.html~RFbbf65e4e.TMP',
     syscall: 'stat' } }
````
In many scenarios the permission issues are very common and a simple `ls` should be capable of ignoring such errors and move ahead with rest of the list (instead of bailing out completely, causing 500 error in the server)

This can be easily fixed by moving the [try .. catch](https://github.com/silexlabs/unifile/blob/master/lib/services/www.js#L207-L220) block inside the for loop (closer to `fs.statSync()`)

I can implement and do a PR for this, if ok with you.  

Also, few other things:
*   Presently only a small portion of `fstat` details are being returned to the caller. I would say, returning the full `fstat` object (+ the usual additional extra derived fields) so that caller can take what they want and ignore the rest, is much better option. For example, user cannot derive mode, creation_time etc. if the results are already pre-filtered at the unifile level.
  *  Now, obviously there is a tradeoff between giving as much info as possible to the caller vs the size of the returned results. The right way should be caller should be able to specifiy which exact fields they need and the `ls` should return exactly those fields. But I would leave it to some future versions, may be v2.0 or v3.0. For now, a full fstat object with compression enabled on the results (at the nodejs express layer) should be fine enough.
  * Another point of concern would be that not all fields returned by `fstat` would be supported by all other services (such as dropbox). But I guess that would have to be taken care by the caller (being at the app level), rather than a middle-ware library like unifile. Besides, caller can choose not to use all fields, if they want to. 
*   It looks like the [fs-extra](https://www.npmjs.com/package/fs-extra#methods) package is fully compatible in-place replacement for `fs`. By switching to the `fs-extra`, more options can be implemented in the future (such as recursive file copies, directory deletions etc.), without extra code. Also `fs-extra` is fully `promise` enabled (just in case in v2.0/v3.0 some one needs it).

**Comment by KrishnaPG** [comment]
Another point worth noting is the caching behavior with `www`. Presently `ETag support` is already monitoring the `ls` results and server is issuing a 304 correctly !!

![image](https://cloud.githubusercontent.com/assets/4610831/10723349/0d5e9412-7be0-11e5-9fe3-ebafad3e72c6.png)

However, at the ground level the computation (the actual retrieval of the directory content and creating the json etc.) is still happening as a full blown request. Perhaps in the future versions, a crude caching layer can be implemented (that monitors the "if modified" request header and compares it with the 'modified time' of top level folder that is being walked.

(Just documenting it here for later reference.)

**Comment by lexoyo** [comment]
+1

**Comment by lexoyo** [comment]
your starting to define what the a v1 should be, I like this

**Comment by KrishnaPG** [comment]
Created PR https://github.com/silexlabs/unifile/pull/34 that implements graceful error handling for few "ignorable errors" while doing ls() and also primitive 304 ETag support for ls().

Now `ls()` (for www) does not waste CPU / Disk cycles on recomputing the folder structure for already visited (and unmodified) folders. Any modifications, as usual lead to a full 200 response

![image](https://cloud.githubusercontent.com/assets/4610831/10813174/ff112162-7e42-11e5-9334-c06597c38f3b.png)
