### ISSUE TITLE
Multi-tenancy

### ISSUE THREAD

**Issue by KrishnaPG** [silexlabs/unifile#33]
What is the best way to implement multi-tenancy with this package?

For example, for the `www`, I would like to have `user x`, mapped to `data/x` as the root folder and `user y` mapped to, say `data/y`, as the root www folder.

This should happen upon successful login (automatically), so that `ls /` for user x gives contents of folder `data/x` and for user y gives contents of `data/y`.

Is it possible in the current version?

**Comment by KrishnaPG** [comment]
One way I can see is: There is this `path resolution` that is [happening](https://github.com/silexlabs/unifile/blob/master/lib/services/www.js#L205) in every method. It could be a good place to have the multi-tenancy redirectors.

For example, the `multitenancy` options could be supported as a `configurable option`, so that users can use this in either single-user mode or multi-user mode. When enabled, something like below could be used to redirect automatically:
````
var user_home = exports.config.multitenant ? request.session.www_user : "";
var resolvedPath = pathModule.resolve(__dirname, exports.config.ROOT+ user_home + path);
````
But the problem with this approach is: one user can never access other user's files, which  makes it impossible to share files with one another (since they never see the full path). I can never access some one's `/file.txt` since the `/` always redirects to my own folder (and not that person's).

**Comment by lexoyo** [comment]
I believe it is close to a test I did some time ago, see this branch
https://github.com/silexlabs/unifile/tree/open-pages

The user logs in with mozilla's persona auth system and then defines a name for his "folder" which is stored in a sqlight table. For example I can login as lexoyo@zzzzzz.com, and set my folder name to lexoyo, then I will have access to a folder accessible at http://myunifileserver.com/lexoyo/

**Comment by KrishnaPG** [comment]
Yes, that is also another possibility. To have a full-blown ACL system, like the one you mentioned `persona auth`, and then be able to have explicit folder names in the path which are accessible only to the right persons.

I looked at the `open-pages` branch and yes it looks on the same lines as I was mentioning above (except I was referring to 'implicit' personal folders that are auto-magically created and always redirected to, so that we do not need an explicit ACL system, while your implementation is focusing on the personal folders as explicit configurable, which gives more control to the user on the folder names and allows sharing but requires a full-blown ACL system). 

Any reason why this branch did not make into the master?  - were there some problems with that design?

**Comment by lexoyo** [comment]
@KrishnaPG I have finished my work on open pages, and I merged it on master
It is disabled by default, here is how to enable it 
https://github.com/silexlabs/unifile/blob/master/samples/simple-api-server.js#L23

**Comment by KrishnaPG** [comment]
Thanks @lexoyo Will pull the latest and try it.

**Comment by KrishnaPG** [comment]
Tried it today after enabling the `options.openPages.ENABLED` option as suggested. Realized that the auth-url also has to be explicitly changed from `www-auth` to `open-pages-auth` to use this correctly.

I liked the way the `unifile` handled the service listing automatically. Is there a way that the `auth listing` can also be handled similar to that? That is, `unifile` will have a single fixed login page (say, `/auth`) and that page will let user pick their favorite login system from the list of all available (similar to how the websites these days do, where they let you pickup any of the supported auths from google, openid, linkedin etc.). Something like the screenshot below
![image](https://cloud.githubusercontent.com/assets/4610831/11111803/ad45d058-8932-11e5-848f-7caf3fd35199.png)


That way, the user code can always make a call to, say `/auth` and presents the user with all logins and then delegates the actual auth to which ever option user picks automatically (without the caller having to explicitly code). It could be `OAuth2`, `open pages` or simple `login form`.

Another point I observed is: looks like the 'responsive resizing' issue popped again (i.e. the login screen does not work well on smaller screens). The fixed width `maincontainer` is creating problem on mobile screens.

![image](https://cloud.githubusercontent.com/assets/4610831/11111641/f4c93db8-8930-11e5-9252-db92d947d182.png)

**Comment by lexoyo** [comment]
> Tried it today after enabling the options.openPages.ENABLED option as suggested. Realized that the auth-url also has to be explicitly changed from www-auth to open-pages-auth to use this correctly.

The auth url is in the response when you call connect. In the case of the FTP/DB/OP it is different

> I liked the way the unifile handled the service listing automatically. Is there a way that the auth listing can also be handled similar to that? That is, unifile will have a single fixed login page (say, /auth) and that page will let user pick their favorite login system from the list of all available (similar to how the websites these days do, where they let you pickup any of the supported auths from google, openid, linkedin etc.). Something like the screenshot below
> That way, the user code can always make a call to, say /auth and presents the user with all logins and then delegates the actual auth to which ever option user picks automatically (without the caller having to explicitly code). It could be OAuth2, open pages or simple login form.

This is a very interesting idea... Only the "simple login form" I do not see what it would be, since the goal is to let a service handle the hosting of the user's files

> Another point I observed is: looks like the 'responsive resizing' issue popped again (i.e. the login screen does not work well on smaller screens). The fixed width maincontainer is creating problem on mobile screens.

Can you make a pull request again?

**Comment by KrishnaPG** [comment]
Yes, `connect` - I forgot about that (and wasn't using it, since it didn't really do much). You are right, it is indeed giving the auth url.

But I guess the caller has to already make a decision as to which service he has to use by the time he calls connect (since it is `www/connect` or `open-pages/connect/`), and I was thinking `open-pages` is just auth mechanism and not a full-blow storage system, as say `www` or `ftp`. Looks like, I am mistaken.

Let me go through this `open-pages` slightly more deep. May be you are right in having separate login forms for each. Will try to get back on this with some more info.

**Comment by lexoyo** [comment]
> But I guess the caller has to already make a decision as to which service he has to use by the time he calls connect (since it is www/connect or open-pages/connect/), and I was thinking open-pages is just auth mechanism and not a full-blow storage system, as say www or ftp. Looks like, I am mistaken.

yes it is indeed: it uses mozilla persona for auth and then creates a folder per user, into which the user can navigate with unifile

**Comment by KrishnaPG** [comment]
Looks like Mozilla is shutting down Persona / Open-pages. 

> On November 30th, 2016, Mozilla will shut down the persona.org services. Persona.org and related domains will be taken offline.

> If you run a website that relies on Persona, you need to implement an alternative login solution for your users before this date.

Ref: https://developer.mozilla.org/en-US/Persona

**Comment by lexoyo** [comment]
Thank you very much @KrishnaPG for the info
This is bad news for the web / privacy / decentralization :(
I will remove open pages then... 

The point of open pages was to address the use case of Indie Hosters (@pierreozoux) and templamatic, who are willing to host websites and/or templates made with Silex, and wish their users could publish content with their account on their plateforms

Webdav may be the solution to this: the user is given an access code to owncloud (or just webdav?) and a folder in webdav would be called `www` or `htaccess` and accessible online

**Comment by KrishnaPG** [comment]
Agreed about decentralization. 

From the storage perspective I too was in the need of reliable options, and the best one that I am actively exploring is [IPFS](https://github.com/ipfs/ipfs).

Wondering how difficult/easy it would be integrate IPFS with Unifine (or such integration even make sense?)

Other similar one is [LAFS](https://www.tahoe-lafs.org/trac/tahoe-lafs).

**Comment by JbIPS** [comment]
Interesting project! The API seems somewhat standard so it shouldn't be too difficult to create a service for it. But I would wait a bit to see how the js impletmentation matures.

**Comment by JbIPS** [comment]
Hello @KrishnaPG! We're on our way to publish the [v1.0.0](https://github.com/silexlabs/unifile/tree/1.0.0) of Unifile. The API and organization is much more clearer now so maybe you want to take a go on implementing IPFS or LAFS?

This will be a great feedback for me with someone else creating backend :smiley:! Thank you

**Comment by KrishnaPG** [comment]
Glad to hear about v1.

Regarding the IPFS, currently I am slightly under the weather. Will let you know once there is any progress on that. Thank you.

**Comment by JbIPS** [comment]
No rush, you can try that anytime you want. Since the connectors are now independent, you don't even need to do a PR, you can create your own repo and use it
