### ISSUE TITLE
Github support in unifile

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/unifile#35]
The goal is to offer a new service in unifile, to use github to store your files. The advantages are 
* free (max size of a repository is 1GB, no limit in the number of repos)
* everything is versioned with git
* one can use it to publish on [github pages](https://pages.github.com/) (which is great quality hosting and free by github themselves)

I have tested the github API, which is quite simple to use, without any SDK or library, just the HTTP API, see my little nodejs test:
https://gist.github.com/lexoyo/932550e8ddbae2ec1d2d

But there is the question of the UI and how we handle repos and branches in unifile. First I thought that

* `/xxx` would be the repo xxx
* `/xxx/yyy/` would be the branch yyy of the repo xxx
* `/xxx/yyy/zzz` would be the folder or file zzz on the branch yyy of the repo xxx

But then I thought that the user will try to store files at the repo or branch level, and will not understand what they are doing. So I see several solutions

* add an `info` field in the json response which tells the user that "at this level, you can not store files, you need to have only folders" or do not even allow to create folders for repos and branches but say "you can not create files or folders here, you need to create a repository in your github acount"
* when the user has authorized unifile to access their github account, ask him to choose a repo (a bit like in open pages when we ask for a name)

The next question would then be how to make people understand how to publish on github pages, they need to publish their site on a branch called gh-pages...

**Comment by JbIPS** [comment]
I'm 100% pro user freedom, but I think making him choose between branch is too much. Only one branch is deployable, this is the only one that should be used.
This means the user log in, choose a repo on his account and the root of gh-pages is shown. This branch is created from master if non-existent.
This should fix your issues and be more intuitive for the user, shouldn't it?

**Comment by lexoyo** [comment]
Interesting

> Only one branch is deployable, this is the only one that should be used.

With other static website generators, people often use master as a working branch, with only source (not published site) and then deploy to gh pages

But I am not against using only gh-pages if it is easier for the user

> This should fix your issues and be more intuitive for the user, shouldn't it?

Yes it does, there is still the need to be able to navigate between repos, even when already logged in

**Comment by lexoyo** [comment]
cc @silexlabs/silex
