### ISSUE TITLE
Unifile next steps

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/unifile#36]
@KrishnaPG got me thinking about the next version of unifile

Here is what I think we should do
- Refactor the API: no more config but option of the API, and the API which could be used in nodejs or with the command line cli or with HTTP calls as it is today
- Make the HTTP API better: use GET, POST, UPDATE, DELETE... 
- Better doc and a website
- Coding style refactoring: Everything should be cleaned up and ported to ES2015, whith promise, the API should mimic Node.js File System api

And here is the details, feel free to help me on this definition of unifile v1
### Refactor the API

In node, for use with slenium or on the server side when you already have a token (the user has authorized the app)

```
var unifile = require('unifile')
var dropbox = new unifile.Dropbox({
    root : 'dropbox',
    app_key : 'ngk5t8312eo4agh',
    app_secret : '7uxqr625pct7zbl'
})
dropbox.connect(function (authorizeUrl) {
    // open authorizeUrl, login and authorise the app
    // then call this
    dropbox.setSession({
        access_token: 'the access_token from dropbox'
    })
    dropbox.ls('/', function(files) {
        console.log('files and folder at the root of your dropbox:', files);
    });
});
```

Use with CLI

```
$ unifile dropbox ls /
waiting for you to authorize the app (a browser window has opened)
app authorized
file 81 Nov 20 23:22 admin.html
file 302 Nov 20 21:24 login.html
folder 136 Nov 20 23:34 node_modules
```

Use the middleware to activate a service and expose the HTTP route

```
var unifile = require('unifile')
var dropbox = new unifile.Dropbox({
    root : 'dropbox',
    app_key : 'ngk5t8312eo4agh',
    app_secret : '7uxqr625pct7zbl'
})
var router = new unifile.Router(dropbox);
var connect = require('connect')
var app = connect()
app.use('/api/dropbox', router)
```
### Make the HTTP API better

use GET, POST, UPDATE, DELETE... 

See these interesting links
*[Google Cloud Storage API Reference](https://cloud.google.com/storage/docs/json_api/v1/)
### Coding style refactoring

Everything should be cleaned up and ported to ES2015, whith promise, the API should mimic Node.js File System api

See these links for the API methods specs
- https://www.chromestatus.com/feature/5452478162141184
- http://cloud-elements.com/hubs/cloud-storage-documents-hub/

**Comment by JbIPS** [comment]
I suggest using ESLint to ensure the code style throughout the repository. And I had some docs on good REST API, I'll post them here as soon as I find them.

**Comment by JbIPS** [comment]
I'm actually reading this a lot: https://developer.github.com/v3/. It's a very well structured API and documentation. This could be an example.

And just to be sure, every service will now be a prototype, right?

**Comment by lexoyo** [comment]
> I'm actually reading this a lot: https://developer.github.com/v3/. It's a very well structured API and documentation. This could be an example.

yes right!

> And just to be sure, every service will now be a prototype, right?

what do you mean exactly?

**Comment by JbIPS** [comment]
Lately I was thinking about splitting this lib. Unifile would only take care of routes declaration and routing. In addition, services (or connector) would be dependencies, loaded at will and declared like a middleware 
```
unifile.use(require('ftp-connector'));
```
This way, you only embed the connectors you want and creating a new connector doesn't imply any modification on Unifile (= don't publish a new version any time a connector changes).

And for the connector development, this mean we can ask for a clear API to implements and get rid of some internal parameters in connector function ('response', 'next',...).

What do you think?

**Comment by lexoyo** [comment]
Wow that's a great idea, like they did with connect body-parser etc.

**Comment by lexoyo** [comment]
:+1:

**Comment by KrishnaPG** [comment]
Also, may be some of these connectors can be reused from [Browser-FS](https://github.com/jvilk/BrowserFS). Especially the `ZipFS`, `WorkerFS` and `FolderAdapter` types of extensions are valuable in different contexts.

**Comment by lexoyo** [comment]
:+1: nice project!
And the idea of using nodejs API is a very good one !

**Comment by lexoyo** [comment]
@JbIPS I have looked at your branch and the sample here
https://github.com/JbIPS/unifile/blob/refacto-api/samples/simple-api-server.js

[Concerning this part of the API (the commands)](https://github.com/JbIPS/unifile/blob/refacto-api/samples/simple-api-server.js#L31)

* This is very nice :+1: 
* You did not take the idea of @KrishnaPG into account and prefered the "promise" version over node nodejs api, is any particular reason?

[Concerning the "useConnector" part](https://github.com/JbIPS/unifile/blob/refacto-api/samples/simple-api-server.js#L22)

* The name could be `use` don't you think?
* and by the way, I use service more than connector but it is in fact a connector to a service. We should choose a way to call this concept and stick to it

[Concerning the "auth" part](https://github.com/JbIPS/unifile/blob/refacto-api/samples/simple-api-server.js#L2)

* no json here? just the URL?

[Concerning the auth callback](https://github.com/JbIPS/unifile/blob/refacto-api/samples/simple-api-server.js#L64)

* you should move this code to the connector, so that you can know when the callback is for which connector?

**Comment by JbIPS** [comment]
> You did not take the idea of @KrishnaPG into account and prefered the "promise" version over node nodejs api, is any particular reason?

I'm not sure what you're referring to. Callback vs Promise? If so, I hate calling 4 functions with callbacks consecutively and that's often the case with Web API.

> The name could be `use` don't you think?

I thought so after I had to write it numerous time :wink:. Connector or service, I don't really care but connector seemed more explicit to me at the time.

> no json here? just the URL?

Don't know what you're talking about, the url must be on the wrong line.

> you should move this code to the connector, so that you can know when the callback is for which connector?

I was going to but I remembered that I cannot declare route in Unifile. But maybe a dynamic function? Any other idea is welcome!

And thank you for the review, I hope will make a next version universally applauded! :smile:

**Comment by JbIPS** [comment]
Do you think we should use the same API as `fs` module? Like `unifile.createReadStream()`?

**Comment by lexoyo** [comment]
+1 to replicate fs API

Maybe something like 
```
var db = new require("unifile").Dropbox({...}); 
db.createReadStream();
```

**Comment by JbIPS** [comment]
Hi guys,

I did some work on my [branch](https://github.com/JbIPS/unifile/tree/refacto-api) to rework the API and use all of the precious inputs in this issue.

Could you take a look at this and give me feedback to ensure we're heading in the right direction? You can find a usage example [here](https://github.com/JbIPS/unifile/blob/refacto-api/samples/simple-api-server.js) and an implementation of the API [here](https://github.com/JbIPS/unifile/blob/refacto-api/lib/unifile-github.js). Thanks!
