### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/unifile#40]
A github and a dropbox apps are used to authorize access to github and dropbox. They have secret and public keys hard coded in [default-config.js](https://github.com/silexlabs/unifile/blob/master/lib/default-config.js). 

We should probably not put this config data there, and force the developer who hosts an instance of unifile to provide his own keys, either in a config.js file, or in env vars.

**Comment by JbIPS** [comment]
Good thinking. Here's an example of how I did it with a Twitter integration: https://github.com/JbIPS/Huddy#how-to-run-it.

We could pass the user's config to a Unifile constructor which validate the presence of mandatory fields before instantiate a service. Of course this config could be dispatched to the proper connector if we rethink the app in a connector way.
