### ISSUE TITLE
Github service in Cloud Explorer

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/unifile#41]
As you may know [Cloud Explorer](http://cloud-explorer.org/) is a web client to use unifile backend

Cloud Explorer has a bug when using the new unifile service "github" by @JbIPS, user has to refresh window after login to access his github content.

I believe the bug occures because [here in the source code of cloud explorer](https://github.com/silexlabs/cloud-explorer/blob/master/src/ce/core/Controller.hx#L1071), `result` is undefined... But I did not investigate further for now

**Comment by JbIPS** [comment]
This was a CE bug and the PR solving it has been merged
