### ISSUE TITLE
Webdav support would be awesome :)

### ISSUE THREAD

**Issue by pierreozoux** [silexlabs/unifile#44]

**Comment by lexoyo** [comment]
+1

**Comment by JbIPS** [comment]
Yes it would! I'll go work on that very soon :wink:

**Comment by lexoyo** [comment]
:yellow_heart:

**Comment by Sergio-Muriel** [comment]
'had started the implementation, but i think you will do it faster, as my nodejs skills are not really good:

https://github.com/Sergio-Muriel/unifile/blob/cloud/lib/services/webdav.js
https://github.com/Sergio-Muriel/unifile/blob/cloud/lib/templates/login-webdav.jade
https://github.com/Sergio-Muriel/unifile/blob/cloud/lib/default-config.js


https://github.com/Sergio-Muriel/unifile/tree/cloud

**Comment by lexoyo** [comment]
Woohoo!!! :boom: 
Can't wai't to test it soon with owncloud :dancer:

**Comment by JbIPS** [comment]
This looks promising @Sergio-Muriel ! Since you started it, you should continue on your way and I can help you with the Node.js tips and tricks :wink: 

To begin with, your [Dav](https://github.com/Sergio-Muriel/unifile/blob/cloud/lib/services/webdav.js#L18) object looks good but it will be better with prototypes. You can check [node-dav](https://github.com/Sergio-Muriel/node-dav/blob/master/lib/dav.js) for inspiration.

**Comment by pierreozoux** [comment]
If you need ownCloud instance for testing, let me know :)

On 18-02-2016 15:28, Jean-Baptiste Richardet wrote:
> This looks promising @Sergio-Muriel ! Since you started it, you should continue on your way and I can help you with the Node.js tips and tricks :wink: 
> 
> To begin with, your [Dav](https://github.com/Sergio-Muriel/unifile/blob/cloud/lib/services/webdav.js#L18) object looks good but it will be better with prototypes. You can check [node-dav](https://github.com/Sergio-Muriel/node-dav/blob/master/lib/dav.js) for inspiration.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/silexlabs/unifile/issues/44#issuecomment-185774572
> 

-- 
I use PGP to protect our privacy, if you want to know more, you can
follow this
https://emailselfdefense.fsf.org/en/

If you have further questions, please do not hesitate to ask.
You can verify my public key here: https://keybase.io/pierreozoux

**Comment by Sergio-Muriel** [comment]
I just added the needed methods for the implementations.
It is based on the ftp service.

The "get" method is not very good. Getting the data to a "tmp file", the streaming it?

**Comment by JbIPS** [comment]
Closed by #53 thank you @Sergio-Muriel !

**Comment by pierreozoux** [comment]
\o/ woo, I can't wait to test!

**Comment by lexoyo** [comment]
please don't wait ! here is a test http://silex-editor.herokuapp.com/

**Comment by pierreozoux** [comment]
I'm amazed :)

Really good!

IndieHosters will announce support soon :)

On 25-02-2016 17:13, Alex Hoyau wrote:
> please don't wait ! here is a test http://silex-editor.herokuapp.com/
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/silexlabs/unifile/issues/44#issuecomment-188883022
> 

-- 
I use PGP to protect our privacy, if you want to know more, you can
follow this
https://emailselfdefense.fsf.org/en/

If you have further questions, please do not hesitate to ask.
You can verify my public key here: https://keybase.io/pierreozoux

**Comment by singchan** [comment]
Hi

I'm integrating this into [Cloud Explorer](https://github.com/silexlabs/cloud-explorer)

For that I need 2 logos for webdav, one 52x52 and  one 110x100

Should we take the logo of owncloud?

**Comment by pierreozoux** [comment]
What about http://fontawesome.io/icon/cloud-upload/ ?

On 26-02-2016 13:43, singchan wrote:
> Hi
> 
> I'm integrating this into [Cloud Explorer](https://github.com/silexlabs/cloud-explorer)
> 
> For that I need 2 logos for webdav, one 52x52 and  one 110x100
> 
> Should we take the logo of owncloud?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/silexlabs/unifile/issues/44#issuecomment-189282599
> 

-- 
I use PGP to protect our privacy, if you want to know more, you can
follow this
https://emailselfdefense.fsf.org/en/

If you have further questions, please do not hesitate to ask.
You can verify my public key here: https://keybase.io/pierreozoux

**Comment by JbIPS** [comment]
It's a bit generic and very close to [Cloud Explorer](http://cloud-explorer.org/) logo. I'm afraid this could be confusing.

But maybe just writing WebDav in it would be enough.

**Comment by pierreozoux** [comment]
Yes, because people might use Cozy/dropbox whatever, so ownCloud would
be misleading

On 26-02-2016 15:33, Jean-Baptiste Richardet wrote:
> It's a bit generic and very close to [Cloud Explorer](http://cloud-explorer.org/) logo. I'm afraid this could be confusing.
> 
> But maybe just writing WebDav in it would be enough.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/silexlabs/unifile/issues/44#issuecomment-189324251
> 

-- 
I use PGP to protect our privacy, if you want to know more, you can
follow this
https://emailselfdefense.fsf.org/en/

If you have further questions, please do not hesitate to ask.
You can verify my public key here: https://keybase.io/pierreozoux

**Comment by JbIPS** [comment]
Actually CozyCloud won't work because they doesn't support WebDav sync :/
-- 
Jean-Baptiste Richardet

**Comment by singchan** [comment]
not sure i understood, but i did this with @lexoyo  :)

![screenshot from 2016-02-26 17-52-23](https://cloud.githubusercontent.com/assets/6483546/13358897/d36a4a02-dcb1-11e5-89bb-34b3a7124c08.png)

![screenshot from 2016-02-26 17-51-49](https://cloud.githubusercontent.com/assets/6483546/13358898/d36ac0ea-dcb1-11e5-8cba-9fd508d8d052.png)

Code: https://github.com/silexlabs/cloud-explorer/commit/06947ebed3ee0de3b99f4fc325416059cf7d0f87

Test: http://silex-editor.herokuapp.com/

**Comment by lexoyo** [comment]
@budislav may help on the icons :)
[This is where you can change the icons](https://github.com/silexlabs/cloud-explorer/tree/master/app/images/default)
Please keep the image sizes
Note that you do not need to use git since github now supports image upload

**Comment by budislav** [comment]
Done :)

I didn't made just new icons, I also re-organised this cloud browser. This mean less steps to login into an account and no warning message popups. Everything can fit into one window, so it does not behave like some trojan virus. Is this possible for mozilla persona and dropbox accounts?

Open images for pixel perfect look
![choose_service-01](https://cloud.githubusercontent.com/assets/3619927/13372221/302205a2-dd3c-11e5-84c7-d04fd81e8513.png)

![service_webserver-01](https://cloud.githubusercontent.com/assets/3619927/13372222/37dde86a-dd3c-11e5-8bb2-892f2beab919.png)

![service_ftp-01](https://cloud.githubusercontent.com/assets/3619927/13372224/3adcab28-dd3c-11e5-9075-825f24d5a710.png)

![browsefiles-01](https://cloud.githubusercontent.com/assets/3619927/13372225/3cecba34-dd3c-11e5-8852-4f6e9700b01b.png)

**Comment by JbIPS** [comment]
Love it! :heart_eyes:

**Comment by lexoyo** [comment]
Wow you really want us to get to work :)) 
Great designs :+1:

**Comment by pierreozoux** [comment]
Yes love it! \o/

**Comment by budislav** [comment]
Thank you all! :)

> you really want us to get to work

Just slowly but surely :)

**Comment by zabojad** [comment]
Hey @budislav ! Great design indeed ! Would you agree to contribute it to [Cloud Explorer](https://github.com/silexlabs/cloud-explorer) ?

The best way would probably be to share it with us with a tool like [Zeplin](http://www.zeplin.io)...

What do you think?

**Comment by budislav** [comment]
Hi @zabojad ! Off course I agree 100%. For zepelin I don't know why I need this but can't try it because I am not using Mac. I have .svg files, this is all vector art.

**Comment by zabojad** [comment]
Hey @budislav ! Zeplin is just a plugin for sketch (do you use sketch ?) to export a design for integration. I don't think you need to be on Mac to use it... It's a very efficient way to share a design with an integrator... I wouldn't have to open any Photoshop or equivalent tool (that I struggle using) to get color codes and font sizes, etc... Maybe there is an equivalent to Zeplin for Adobe tools...

If you don't know how to do that, just share what you have and we will manage to integrate it anyway ^^...

**Comment by budislav** [comment]
@zabojad Sketch is only available for Mac users and I have PC so I can't use Zepelin. I used Adobe Illustrator but I can export as .svg file so ou can open it in open source alternative like Inkscape. Unfortunately there is no something like Sketch for Windows. Adobe is preparing something they call project comet http://landing.adobe.com/en/na/products/creative-cloud/comet/229818-notifyme.html but it is not available yet. So I can give you only .svg or .ai(adobe illustrator)  files.

**Comment by lexoyo** [comment]
+1 to not use proprietary software, +2 for not adobe ;)

**Comment by budislav** [comment]
@lexoyo you forgot +1 for not Mac :)
@zabojad used fonts are Open Sans (bold, regular, light)

[Silex.zip](https://github.com/silexlabs/unifile/files/154694/Silex.zip)
