### ISSUE TITLE
tmp folder filled by unifile transfers

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/unifile#45]
Yesterday Silex was down all day long because the folder `/lamp0/tmp/` was full of temp files

This must be caused by unifile somehow?

**Comment by lexoyo** [comment]
I found out that `/lamp0/tmp` is nodejs temp folder for file upload. Files should be cleaned up after upload [here](https://github.com/silexlabs/unifile/blob/269f59e5599dfd95c57c868e64228a32e080864b/lib/core/router.js#L124) and [here](https://github.com/silexlabs/unifile/blob/269f59e5599dfd95c57c868e64228a32e080864b/lib/core/router.js#L214)

And I should have used streams :-1:

**Comment by JbIPS** [comment]
Fixed with newest version
