### ISSUE TITLE
Resume the form data entered by the user when logging with ftp

### ISSUE THREAD

**Issue by Sergio-Muriel** [silexlabs/unifile#48]
When logging on a service with ftp, and an error occured, the message
`Invalid access codes`
is displayed and the form is displayed again, but the data previously entered by the user  are lost, and he has to reenter all the form data.

**Comment by JbIPS** [comment]
Hello Sergio,

You're right, when the wrong credentials are sent, we just refresh the form with the template https://github.com/silexlabs/unifile/blob/master/lib/templates/login-ftp.jade. I'll check if there is a way to "store" the inputs or not erase them on refresh.

**Comment by lexoyo** [comment]
is this the same issue as https://github.com/silexlabs/unifile/issues/47 ?

**Comment by Sergio-Muriel** [comment]
Nop. 
This bug is about the data of the form when entering wrong information.

#47 is a crash i have when using wrong credentials

**Comment by Sergio-Muriel** [comment]
Fixed on master
