### ISSUE TITLE
Multi accounts login

### ISSUE THREAD

**Issue by Sergio-Muriel** [silexlabs/unifile#51]
It will be awesome to be able to have a multi-login for the  dropbox/ftp/... services, without having to disconnect/reconnect.

The main problem is that the **/exec/ls/path** like commands does not specifiy the account they are asking, so we cannot know which connected account use.

Maybe with a query parameter?

**Comment by JbIPS** [comment]
This is tricky. I don't think OAuth based services would let us do that. Maybe we can do this for FTP or WebDav (when support comes).

I'm working on a new API for Unifile in my [fork](https://github.com/JbIPS/unifile/tree/refacto-api), maybe we could add it nicely here :smiley:

**Comment by JbIPS** [comment]
I think this issue is a duplicate for #33
