### ISSUE TITLE
github service, callback with localhost

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/unifile#54]
Hello

Here is what happens with the github service online (silex preprod)
http://preprod.silex.me/api/v1.0/github/connect/

Follow the auth url and you will see that the callback is hard coded :deciduous_tree:

**Comment by lexoyo** [comment]
also with localhost, the callback is `http://localhost:6805/oauth-callback?code=8cf757486243e652dc4c` which gives me 
```
Cannot GET /oauth-callback?code=220ad41a7598863fc409
```

**Comment by JbIPS** [comment]
We can't give any callback URL to GH OAuth so Silex will need its own GH application for production
