### ISSUE TITLE
an issue with github service

### ISSUE THREAD

**Issue by singchan** [silexlabs/unifile#57]
I use github service
I saved a website many times and published many times
It made a repo with so many commits github refuses to save
I squashed these commits and now I am able to save again :'(

**Comment by JbIPS** [comment]
The problem is that, for now, CloudExplorer create a commit for each modified file. 
I'm working on a new version that will enable batch modifications. This way, saving and publishing will only be a commit each. This will greatly help your issue :smile:
-- 
Jean-Baptiste Richardet
