### ISSUE TITLE
remoteStorage protocol consideration

### ISSUE THREAD

**Issue by kantoche** [silexlabs/unifile#58]
Do you plan the use of an open protocol like RemoteStorage?
https://remotestorage.io/

**Comment by JbIPS** [comment]
I didn't know about this protocol. At first sight, it looks like it's doing the same thing than unfifile: getting remote cloud storage under the same API. If it is, I don't see the point. If it's not, we'll need to clarify how we can make it work and try it! 

Thank you for the idea

**Comment by lexoyo** [comment]
I feel like it is more of a specification than an implementation. The website is not very clear

**Comment by lexoyo** [comment]
Remote storage is linking to @pierreozoux Indie Hoster website here
https://wiki.remotestorage.io/Servers

Pierre, do you know what is remoteStorage? A project, a service, a specification?

**Comment by pierreozoux** [comment]
So ;)

I think I already mentioned it somewhere in one of our discussion.

First there was [unhosted](http://unhosted.org/), it is a philosophy to develop webapp to fix the problem of the app embedding the data backend for the user. In the "unhosted" context, the user is free to choose is backend for his data.
This is the "philosophie".

As part of their work, they wrote an RFC to specify a protocol - remoteStorage.
https://remotestorage.io/

They also wrote a Server side implementation (in node), and there is also a php version available.

And, this is becoming interesting, they also wrote a client that handle many things, like offline first, or let the user choose among dropbox, google drive or a free software data backend - remoteStorage.

Actually unifile is a kind of concurrent to remoteStorage, and I guess it would make a lot of sense to migrate to remoteStorage as there is a wider support :)
(I'll cross post this to the mailing list of unhosted to let people complete my view).

The main free software project using unhosted - remoteStorage is (in my opinion) https://laverna.cc/app/

I can provide you free accounts to a remoteStorage instance if you need.

**Comment by KrishnaPG** [comment]
Was going through the remotestorage and 5apps sites. Looks interesting, but not clear: how is it different from, say DropBox or similar?

Any app that has DropBox capability can utilize the user-specified dropbox storage as its storage. What is remotestroage doing different?

**Comment by JbIPS** [comment]
I think this the 'Standard and Free' version of Dropbox and not linked to a service.

**Comment by JbIPS** [comment]
Just to let you know I'm currently playing with RemoteStorage (I'm glad to accept your hosting offer @pierreozoux :smile: ).

I'm having a hard time with module definition so if you have any experience with it, it's very welcome!

**Comment by JbIPS** [comment]
I forgot to let you know about my recent success with RemoteStorage :smile:. The official npm connector is not suitable for Node.js so I had to start it from scratch but it work! I'll soon make a PR on the v1.0.0 branch. Thank you @pierreozoux for the test server!

**Comment by JbIPS** [comment]
This is now on v1.0.0!

**Comment by pierreozoux** [comment]
you mean I can use RS as a data backend? \o/ Can youping when available on prod?

**Comment by JbIPS** [comment]
Yes you can :smile:! And I'm sure you'll know when v1 hits npm. As for Silex integration, I'll leave @lexoyo tell you
