### ISSUE TITLE
npm version

### ISSUE THREAD

**Issue by KrishnaPG** [silexlabs/unifile#64]
npm is listing 0.0.60 as the latest version, but the git (here) is showing 0.0.59
![image](https://cloud.githubusercontent.com/assets/4610831/17081663/e7af26e4-517e-11e6-8e72-1cca13b5d85b.png)

**Comment by KrishnaPG** [comment]
Not sure what is happening, but the version on the git ([here](https://github.com/silexlabs/unifile/blob/master/lib/templates/login.css#L51)) is showing correct css file (sometime back I merged to correct the [responsive sizing](https://github.com/silexlabs/unifile/pull/59) issue of login page)
But from NPM, both 0.0.60, 0.0.59 are both having the same old login.css code without the corrections.

**Comment by JbIPS** [comment]
Hello @KrishnaPG !

Sorry for the NPM mess, we'll soon fix that with the publication of the v1.0.0 version :wink:
