### ISSUE TITLE
Default app keys

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/unifile#65]
I think we should provide app keys by default for Dropbox and Github, but I am not sure that this is possible because sometimes the app will have the port and callbacks...

Otherwise a doc about where to get it and how to set it up with unifile would be helpful.

**Comment by JbIPS** [comment]
The GitHub application has to provide a callback URL and cannot be overridden so we'll have to set `http://localhost:6805`. But I think that the best solution is indeed a documentation on how to setup your own application per target (maybe on the Readme of each repository if we split the targets).

**Comment by JbIPS** [comment]
Github and Dropbox connectors now redirect to the app creation on the respective platforms. Regarding the default app keys, I'll close this in favor of #40

**Comment by lexoyo** [comment]
Great idea!
