### ISSUE TITLE
SSH consideration

### ISSUE THREAD

**Issue by JbIPS** [silexlabs/unifile#75]
What do you think about have a SSH connector? A lot of Node.js already implemented SSH client and this would mean a lot of newly available servers for Unifile users :smiley:

**Comment by lexoyo** [comment]
Good idea!! This would make cli possible
It is a bit like webdav server right?

**Comment by JbIPS** [comment]
It's a bit like WebDav, but more secured. That's precisely what would be the main diffucilty IMO: how will we create the session ? Key, password, other?

**Comment by lexoyo** [comment]
hmm ok
maybe with env vars
the main advantage I see with webdav is that it can be added to the file browsers and used like a local drive

**Comment by JbIPS** [comment]
Closed by 21a25bf55b5e087fb64224f4d7d140ec51b17421
