### ISSUE TITLE
rclone

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/unifile#76]
[rclone](http://rclone.org/) looks like an open source competitor of unifile. It is interesting to me ang [the supported services](http://rclone.org/docs/) can give us ideas. Maybe the code too?

**Comment by lexoyo** [comment]
[this doc](http://rclone.org/dropbox/) will give you a good idea of how it works

**Comment by lexoyo** [comment]
a use case covered by rclone is to move big amount of data from one cloud to another with the command line

could it be done with unifile?

**Comment by JbIPS** [comment]
Yes it could, thanks to the stream API. Buy I think what's missing is recursive features to move a whole folder.

**Comment by mudcube** [comment]
There's a package for BrowserFS for rsync'ing. Since BrowserFS shares a similar API to Unifile (both are based on NodeJS) the package might be able to plug into Unifile as well: https://github.com/kruemelo/fs-rsync
