### ISSUE TITLE
Dropbox specific way to list root folder

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/unifile#77]
I have an error when I try to list "/": 

```
Error in call to API function "files/list_folder": request body: path: Specify the root folder as an empty string rather than as "/".
```

It comes from dropbox js sdk and it is [discussed here](https://github.com/dropbox/dropbox-sdk-obj-c/issues/32):

> This is expected. With Dropbox API v2, the root is expressed as empty string "", and non-root paths are expressed with a leading slash, e.g. "/test.txt".

Do you think that Unifile should include a workaround? I think so... I can add this myself, just tell me if what you think?

**Comment by JbIPS** [comment]
I think so too. Actually it's already [there](https://github.com/silexlabs/unifile/blob/1.0.0/lib/unifile-dropbox.js#L106), but lack the support of your use case. 

But I think you won't have any troubles fixing that :wink:

**Comment by JbIPS** [comment]
Closed by https://github.com/silexlabs/unifile/commit/722ab9e4ac8fb089ea9495f2f5ee7fd69feba9be

**Comment by erojiraiya** [comment]
Hi,
I am getting same error while validating the new custom backup. Also, account backups are not transferred to dropbox. It is strange that system backup is transferred and account backup is not. I do not know where to check for the solution. Please help.

Thank You
