### ISSUE TITLE
Give the user the possibility to change connector infos

### ISSUE THREAD

**Issue by JbIPS** [silexlabs/unifile#90]
The user should be able to set a different name/description for a given connector (for locale purpose or customization) without redefining the connector completely.

**Comment by lexoyo** [comment]
I was thinking about this... Would you use inheritance?

In my use case I think I need to override info and also force some parameters values. For example set the host for ftp or at least the default value

**Comment by JbIPS** [comment]
I was thinking extra options in the connector constructor. 

As for default values, there is none but I think you want to set some in the view like the logging form

**Comment by lexoyo** [comment]
Good ideas!
