### ISSUE TITLE
FTP login error

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/unifile#95]
When there is an authentication error, the FTP service logs something like this in the console `ERROR { Error: Login authentication failed` and returns this in the response:
![screenshot from 2017-09-22 12-18-46](https://user-images.githubusercontent.com/715377/30756461-7346d796-9f90-11e7-8a08-4c4d3d8a7906.png)

1- Do you think we should display an error page, or is the JSON on purpose? 
2- Maybe also more data about why it failed?
3- There is the login and password in the URL of the callback in GET, do you think we could make it more secure? (POST at least or in the session)

**Comment by JbIPS** [comment]
> Do you think we should display an error page, or is the JSON on purpose?

I think the app should display an "Invalid user/password" type error

> There is the login and password in the URL of the callback in GET, do you think we could make it more secure? (POST at least or in the session)

That's bad... It sure would be better to **not** have this plain in the open. I'll try to figure something out

**Comment by lexoyo** [comment]
> I think the app should display an "Invalid user/password" type error

oh you mean the app calling unifile
yes of course, that's good
so you think of a mechanism to retrieve the error in the callback?

**Comment by JbIPS** [comment]
About the credentials in the URL, it's actually not from Unifile. If you used my sample server, it says [here](https://github.com/silexlabs/unifile/blob/master/samples/public/ftp_login.html#L10) to send the data with `GET` (I shouldn't be doing that). By all means, use `POST`!

To retrieve the error, just add `.catch()` to the login method. You can look at the [tests](https://github.com/silexlabs/unifile/blob/master/test/unifile-ftp.js#L200) to get examples 😉
